[package]
name = "rust-web-scrape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.17"
serde_json = "1.0.96"
tokio = { version = "1.28.1", features = ["full"] }
